/**
 * testCenter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyModel from './PropertyModel';

/**
 * The MappingModel model module.
 * @module client.projectDemo.client.teams/client.projectDemo.client.teams.model/MappingModel
 * @version 1.0.0
 */
class MappingModel {
    /**
     * Constructs a new <code>MappingModel</code>.
     * @alias module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/MappingModel
     * @param properties {Array.<module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/PropertyModel>} 
     */
    constructor(properties) { 
        
        MappingModel.initialize(this, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, properties) { 
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>MappingModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/MappingModel} obj Optional instance to populate.
     * @return {module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/MappingModel} The populated <code>MappingModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MappingModel();

            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [PropertyModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MappingModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MappingModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MappingModel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['properties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['properties'])) {
                throw new Error("Expected the field `properties` to be an array in the JSON data but got " + data['properties']);
            }
            // validate the optional field `properties` (array)
            for (const item of data['properties']) {
                PropertyModel.validateJSON(item);
            };
        }

        return true;
    }


}

MappingModel.RequiredProperties = ["properties"];

/**
 * @member {Array.<module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/PropertyModel>} properties
 */
MappingModel.prototype['properties'] = undefined;






export default MappingModel;

