/**
 * testCenter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestrictModel model module.
 * @module client.projectDemo.client.teams/client.projectDemo.client.teams.model/RestrictModel
 * @version 1.0.0
 */
class RestrictModel {
    /**
     * Constructs a new <code>RestrictModel</code>.
     * @alias module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/RestrictModel
     */
    constructor() { 
        
        RestrictModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestrictModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/RestrictModel} obj Optional instance to populate.
     * @return {module:client.projectDemo.client.teams/client.projectDemo.client.teams.model/RestrictModel} The populated <code>RestrictModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestrictModel();

            if (data.hasOwnProperty('enumerateList')) {
                obj['enumerateList'] = ApiClient.convertToType(data['enumerateList'], ['String']);
            }
            if (data.hasOwnProperty('maxValue')) {
                obj['maxValue'] = ApiClient.convertToType(data['maxValue'], 'Number');
            }
            if (data.hasOwnProperty('minValue')) {
                obj['minValue'] = ApiClient.convertToType(data['minValue'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestrictModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestrictModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['enumerateList'])) {
            throw new Error("Expected the field `enumerateList` to be an array in the JSON data but got " + data['enumerateList']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} enumerateList
 */
RestrictModel.prototype['enumerateList'] = undefined;

/**
 * @member {Number} maxValue
 */
RestrictModel.prototype['maxValue'] = undefined;

/**
 * @member {Number} minValue
 */
RestrictModel.prototype['minValue'] = undefined;






export default RestrictModel;

